### ISSUE TITLE
Project Setup and Basic Backend

### ISSUE THREAD

**Issue by sinmi-hub** [sinmi-hub/AGST#1]
Tasks:

- Set up Git for version control, and github for repo. 
- Set up a Python development environment with Flask. Specifically a virtual environment.
- Configure MongoDB Atlas and establish a connection from Flask. 
- Create basic data models for educators, lesson plans, and videos in Flask.
- Write simple Flask routes to test database connectivity and basic CRUD operations.

**Comment by sinmi-hub** [comment]
Currently 11/13 - First 3 issues in this sprint has been resolved. Goal is to complete the last 2 issues by 11/15
@JosephLourduLouis Please add a comment when you are done with the first  two. Since the last two are backend features, I will be getting them done. If you would be like to involved, let me know. But I do plan to use your help with the front end.

**Comment by JosephLourduLouis** [comment]
Hey man, I'd love to be involved. I am just confused a bit, do you want to
meet up some time today or did you still wanna do sometime later this week?
